### PR TITLE
Add mailchimp subscriber form

### PR DESCRIPTION
**Pull request by iLeonelPerea**

### CODE REVIEW

**Comment by AAlvz** [comment]
It'd better to add the `suscribe` button after `Our features` and before the last blue part at the bottom. A big button: 

```
We're about to launch! Want to get more info or be a part of our beta?
<button> Subscribe now to our newsletter </button> 
```

**Comment by AAlvz** [comment]
What do you think, @thetonymaster ? Check that message above ^^^

**Comment by thetonymaster** [comment]
Kewl

**Comment by iLeonelPerea** [comment]
Now how looks?

screen shot 2016-08-15 at 09 12 23

**Comment by AAlvz** [comment]
This would be better change to a button saying `request invite` that leads to a google forms that asks for the name, email, ando some basic questions: 

```
What hosting provider are you using right now? (e.g. AWS, DigitalOcean, Google Cloud, Heroku)
Which of the following applies to your tech stack? *
Python (Flask, Django, etc)
Ruby (Rails, Sinatra, etc)
PHP
Java
C
NodeJS
Go

What's your biggest problem or time-sink with your infrastructure and code deploys right now?

Do you use Staging or QA environments?
```

**Comment by thetonymaster** [comment]
Should we also ask if they use Staging or QA environments?

**Pull request merged**
